### ISSUE TITLE
As Redrossa, I can verify that my newly input entries before compiled are correct, so that I can trust that the compilation is the source of truth for future input entries

### ISSUE THREAD

**Issue by redrossa** [redrossa/adfire#14]
# Description

Recording individual entries can get very numerous, and a minor misinput can throw off balances that is hard to debug. We can solve this by making the compiled output a source of truth, so that future input entries can just add on top of that. What this means is trusting that the compiled output has no errors, and that all errors are discovered in the batch of input entries, which is assumed to be smaller than the batch of compiled output entries. Overall, this process would make it easier to debug errors (if there is any in the input), and give a peace of mind that the compiled output are free of errors. Once the input entries are verified to be free of errors, it is added into the compiled output entries, providing an updated source of truth for the next batch of input.

# Acceptance Criteria

- [x] CLI format produces a checksum file alongside the formatted file
- [x] If input record subset contained in the checksum produces a different checksum, throw error
- [x] Checksum is determined by `"posted"` entries with the following column conditions:
  - [x] Fixed values:
    - `date`
    - `entity`
    - `amount`
    - `worth`
    - `status`
    - `account`
    - `mask`
    - `type`
    - `subtype`
  - [x] Semi-fixed, i.e. from correct optional values (e.g. correct values and offsets for balances, fixed custom values for IDs) is allowed, other than that not allowed:
    - `id.transaction`
    - `balances.limit`
- [x] Prevents update records to **remove** and **change** the identity of a posted entry
- [x] Allows new entries to be added at any date, i.e. not limited to the bottom of the record, but can also be in the past

**Comment by redrossa** [comment]
# Tasks

- [ ] Use `pd.util.hash_pands_object` which produces a Series of hashes indexed for each row.
- [ ] Make sure the record being hashed has filled all values for the fixed value columns, e.g. `id.transaction` doesn't have auto provided values if single-leg transaction and not manually provided.
- [ ] For the hash, may want to use `id.transaction` as the index

**Comment by redrossa** [comment]
`balances.available` is no longer a required to be included in the hash because pending entries may change dates that would affect `balances.available` of all subsequent entries. Changes of this value in subsequent entries realistically aren't meaningful to the integrity of the record, so we can exclude it.

**Comment by redrossa** [comment]
Same goes for `balances.current` in order to allow adding entries in the past
